import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import resourses.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christos
 */
public class AccountNew extends javax.swing.JPanel {
    private final JPanel parent;
    private final JTabbedPane tabs;
    private int type;
    Statement  statement       = null;
    /**
     * Creates new form NewCategory
     * @param tabs
     * @param parent
     */
     public AccountNew(JTabbedPane tabs,JPanel parent) {
         type=1;
        this.parent=parent;
        this.tabs=tabs;
        initComponents();
        ErrorLabel.setVisible(false);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        clientNameField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        SaveCategory = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        passwordtField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Create new Account");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Username");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 79, 70, -1));

        clientNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientNameFieldFocusGained(evt);
            }
        });
        clientNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameFieldActionPerformed(evt);
            }
        });
        add(clientNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 79, 93, -1));

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 98, 50));

        SaveCategory.setText("Save");
        SaveCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCategoryActionPerformed(evt);
            }
        });
        add(SaveCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 96, 50));

        ErrorLabel.setText("Already exists");
        add(ErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 251, 40));

        passwordtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordtFieldFocusGained(evt);
            }
        });
        passwordtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtFieldActionPerformed(evt);
            }
        });
        add(passwordtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 117, 93, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Password");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 117, 60, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Administrator");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Normal");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void clientNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNameFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        tabs.setSelectedComponent(parent);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SaveCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCategoryActionPerformed
        int lastid = DatabaseInfo.lastID("\"user\"");//finds last id
        String tempcommand = "INSERT INTO \"user\" (id,name,password,type) VALUES ("+(lastid+1)+",'"+clientNameField.getText()+"','"+passwordtField.getText()+"',"+type+")";
        DatabaseInfo.executeInsert(tempcommand);
        tabs.setSelectedComponent(parent);
        JOptionPane.showMessageDialog(null, "successfully added");
    }//GEN-LAST:event_SaveCategoryActionPerformed

    private void clientNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientNameFieldFocusGained
        // TODO add your handling code here:
        ErrorLabel.setVisible(false);
    }//GEN-LAST:event_clientNameFieldFocusGained

    private void passwordtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordtFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtFieldFocusGained

    private void passwordtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtFieldActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    type=1;        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    type=0;        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton SaveCategory;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField clientNameField;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField passwordtField;
    // End of variables declaration//GEN-END:variables
}
