
import java.awt.Point;
import javax.swing.JPanel;
import resourses.Account;
import resourses.Category;
import resourses.Client;
import resourses.Product;
import resourses.Supplier;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christos
 */
public class AccountEditID extends javax.swing.JFrame {

    private final int clientid;
    private final AccountEdit parent;
    private final Account account ;
    /**
     * Creates new form EditProduct
     * @param d
     * @param n
     */
    public AccountEditID(AccountEdit d,int n) {
        parent=d;
        parent.setEnabled(false);
        clientid=n;
        account = DatabaseInfo.loadAccountID(clientid);
        initComponents();
        setFields();
    }


    private void setFields(){//get the fields from database
        NameTxt.setText(account.name);
        PasswordlTxt.setText(account.password);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductPageWarningLabel = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        ProductPageBackButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PasswordlTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        topbar = new javax.swing.JPanel();
        exit_button = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductPageWarningLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(ProductPageWarningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 342, 27));
        getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 130, 30));

        ProductPageBackButton.setText("Back");
        ProductPageBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductPageBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ProductPageBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 98, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Name");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 57, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 96, 50));
        getContentPane().add(PasswordlTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 130, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Password");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 80, 30));

        topbar.setBackground(new java.awt.Color(59, 122, 208));

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconx.png"))); // NOI18N
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_buttonMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Edit Account");

        javax.swing.GroupLayout topbarLayout = new javax.swing.GroupLayout(topbar);
        topbar.setLayout(topbarLayout);
        topbarLayout.setHorizontalGroup(
            topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                .addComponent(exit_button)
                .addGap(12, 12, 12))
        );
        topbarLayout.setVerticalGroup(
            topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topbarLayout.createSequentialGroup()
                .addGroup(topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topbarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(exit_button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductPageBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductPageBackButtonActionPerformed
        this.setVisible(false);
        parent.setEnabled(true);
    }//GEN-LAST:event_ProductPageBackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String command = "UPDATE \"user\"\n" +
        "SET name = '"+NameTxt.getText()+"',password = '"+PasswordlTxt.getText()+"' "+
        "\n WHERE id ="+clientid;
        DatabaseInfo.executeInsert(command);

        parent.setEnabled(true);
        this.setVisible(false);
        parent.refreshcontent();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       parent.setEnabled(true);

    }//GEN-LAST:event_formWindowClosed

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseClicked
        // TODO add your handling code here:
        parent.setEnabled(true);
        this.setVisible(false);
 
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();    // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);    
    }//GEN-LAST:event_formMouseDragged
    private static Point point = new Point();
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PasswordlTxt;
    private javax.swing.JButton ProductPageBackButton;
    private javax.swing.JLabel ProductPageWarningLabel;
    private javax.swing.JLabel exit_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel topbar;
    // End of variables declaration//GEN-END:variables
}
