import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import resourses.Category;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christos
 */
public class CategoryNew extends javax.swing.JPanel {
     private final Category Categories[] = DatabaseInfo.loadCategories();
    private Connection dbConnection = null;
    private final JPanel parent;
    private final JTabbedPane tabs;
    Statement  statement       = null;
    /**
     * Creates new form NewCategory
     * @param tabs
     * @param parent
     */
     public CategoryNew(JTabbedPane tabs,JPanel parent) {
        this.parent=parent;
        this.tabs=tabs;
        initComponents();
        ErrorLabel.setVisible(false);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        categoryNameField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        SaveCategory = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Create new Category");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Name");

        categoryNameField.setText("0");
        categoryNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                categoryNameFieldFocusGained(evt);
            }
        });
        categoryNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryNameFieldActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        SaveCategory.setText("Save");
        SaveCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCategoryActionPerformed(evt);
            }
        });

        ErrorLabel.setText("Already exists");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(SaveCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(categoryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(categoryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoryNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryNameFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        tabs.setSelectedComponent(parent);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SaveCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCategoryActionPerformed
        if(checkExistance()){ErrorLabel.setVisible(true);return ;}
        int lastid = DatabaseInfo.lastID("product_category");//finds last id
        String tempcommand = "INSERT INTO product_category (id,name,parent_category_id)\n VALUES ("+(lastid+1)+",'"+categoryNameField.getText()+"',null);";
        DatabaseInfo.executeInsert(tempcommand);
        tabs.setSelectedComponent(parent);
        JOptionPane.showMessageDialog(null, "successfully added");
    }//GEN-LAST:event_SaveCategoryActionPerformed

    private void categoryNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_categoryNameFieldFocusGained
        // TODO add your handling code here:
        ErrorLabel.setVisible(false);
    }//GEN-LAST:event_categoryNameFieldFocusGained
    private boolean checkExistance(){
        for(int i=0;i<Categories.length;i++){
            if(Categories[i].name.equals(categoryNameField.getText())){
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton SaveCategory;
    private javax.swing.JTextField categoryNameField;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    // End of variables declaration//GEN-END:variables
}
