import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import resourses.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christos
 */
public class ClientNew extends javax.swing.JPanel {
    private final Client Clients[] ;
    private final JPanel parent;
    private final JTabbedPane tabs;
    Statement  statement       = null;
    /**
     * Creates new form NewCategory
     * @param tabs
     * @param parent
     */
     public ClientNew(JTabbedPane tabs,JPanel parent) {
        this.parent=parent;
        this.tabs=tabs;
        initComponents();
        ErrorLabel.setVisible(false);
        Clients = DatabaseInfo.loadClient();
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        clientNameField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        SaveCategory = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        clientField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Create new client");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Fullname");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 79, 57, -1));

        clientNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientNameFieldFocusGained(evt);
            }
        });
        clientNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameFieldActionPerformed(evt);
            }
        });
        add(clientNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 79, 93, -1));

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 98, 50));

        SaveCategory.setText("Save");
        SaveCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCategoryActionPerformed(evt);
            }
        });
        add(SaveCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 96, 50));

        ErrorLabel.setText("Already exists");
        add(ErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 251, 40));

        clientField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientFieldFocusGained(evt);
            }
        });
        clientField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientFieldActionPerformed(evt);
            }
        });
        add(clientField, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 117, 93, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Email");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 117, 57, -1));

        PhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneFieldFocusGained(evt);
            }
        });
        PhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneFieldActionPerformed(evt);
            }
        });
        add(PhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 155, 93, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Phone");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 155, 57, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void clientNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientNameFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        tabs.setSelectedComponent(parent);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SaveCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCategoryActionPerformed
        if(checkExistance()){ErrorLabel.setVisible(true);return ;}
        int lastid = DatabaseInfo.lastID("client");//finds last id
        String tempcommand = "INSERT INTO client (id,full_name,email,phone) VALUES ("+(lastid+1)+",'"+clientNameField.getText()+"','"+clientField.getText()+"',"+PhoneField.getText()+")";
        DatabaseInfo.executeInsert(tempcommand);
        tabs.setSelectedComponent(parent);
        JOptionPane.showMessageDialog(null, "successfully added");
    }//GEN-LAST:event_SaveCategoryActionPerformed

    private void clientNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientNameFieldFocusGained
        // TODO add your handling code here:
        ErrorLabel.setVisible(false);
    }//GEN-LAST:event_clientNameFieldFocusGained

    private void clientFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_clientFieldFocusGained

    private void clientFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientFieldActionPerformed

    private void PhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFieldFocusGained

    private void PhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFieldActionPerformed
    private boolean checkExistance(){
        for(int i=0;i<Clients.length;i++){
            if(Clients[i].name.equals(clientNameField.getText())){
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton SaveCategory;
    private javax.swing.JTextField clientField;
    private javax.swing.JTextField clientNameField;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    // End of variables declaration//GEN-END:variables
}
