
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 *CHECK FOR CONENCTION WITH THE DATABASE SO THE PROGRAM WONT CRASH 
 */

/**
 *
 * @author Christos
 */
public class CreateUser extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    private Login L ;
    public CreateUser(Login l) {
       this.L=l;
       setJFrameIcon();
        initComponents();
        setLocation(500, 300);
        
    }
    private void setJFrameIcon(){
     try {
            this.setIconImage(ImageIO.read(new File("src/images/LogoM.png")));
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        login_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        exit_button = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        username_field = new javax.swing.JTextField();
        password_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginForm.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(59, 122, 208));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 500));

        login_panel.setBackground(new java.awt.Color(59, 122, 208));
        login_panel.setMaximumSize(new java.awt.Dimension(400, 500));
        login_panel.setMinimumSize(new java.awt.Dimension(400, 500));
        login_panel.setPreferredSize(new java.awt.Dimension(400, 500));
        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(41, 42, 45));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconx.png"))); // NOI18N
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 10, 25, 25));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(200, 224, 240));
        jLabel18.setText("Productive");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        login_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        jButton2.setBackground(new java.awt.Color(221, 229, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(59, 122, 208));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        login_panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 160, 50));

        username_field.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        username_field.setForeground(new java.awt.Color(109, 109, 109));
        username_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username_field.setText("Username");
        username_field.setCaretColor(new java.awt.Color(109, 109, 109));
        username_field.setMaximumSize(new java.awt.Dimension(245, 60));
        username_field.setMinimumSize(new java.awt.Dimension(245, 60));
        username_field.setPreferredSize(new java.awt.Dimension(245, 60));
        username_field.setSelectedTextColor(new java.awt.Color(141, 141, 141));
        username_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_fieldFocusLost(evt);
            }
        });
        username_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                username_fieldMouseClicked(evt);
            }
        });
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        login_panel.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 240, 60));

        password_field.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        password_field.setForeground(new java.awt.Color(109, 109, 109));
        password_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password_field.setText("Password");
        password_field.setCaretColor(new java.awt.Color(109, 109, 109));
        password_field.setMaximumSize(new java.awt.Dimension(245, 60));
        password_field.setMinimumSize(new java.awt.Dimension(245, 60));
        password_field.setPreferredSize(new java.awt.Dimension(245, 60));
        password_field.setSelectedTextColor(new java.awt.Color(141, 141, 141));
        password_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_fieldFocusLost(evt);
            }
        });
        password_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                password_fieldMouseClicked(evt);
            }
        });
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });
        login_panel.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 240, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(200, 224, 240));
        jLabel2.setText("Create a new Administrator");
        login_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseClicked
        // TODO add your handling code here:
        L.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
        
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String username = username_field.getText();
        String password = password_field.getText();
        if(username_field.getText().equals("Username")){JOptionPane.showMessageDialog(null, "enter a username");return;}
        if(password_field.getText().equals("Password")){JOptionPane.showMessageDialog(null, "enter a Password");return;}
        int lastid=DatabaseInfo.lastID("\"user\" ");
        String command ="insert into \"user\"  (id,name,password,type) "
                + "values( "+(lastid+1)+" , '"+username+"' , '"+password+"' ,"+0+" )";
        DatabaseInfo.executeInsert(command);
        JOptionPane.showMessageDialog(null, "succesfull added");
        L.setEnabled(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void username_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_fieldFocusLost
        // TODO add your handling code here:
        if(username_field.getText().equals("")){username_field.setText("Username");}
    }//GEN-LAST:event_username_fieldFocusLost

    private void username_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_fieldMouseClicked
        // TODO add your handling code here:
        if(username_field.getText().equals("Username")){username_field.setText("");}

    }//GEN-LAST:event_username_fieldMouseClicked

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void password_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_fieldFocusLost
        if(password_field.getText().equals("")){password_field.setText("Password");}
    }//GEN-LAST:event_password_fieldFocusLost

    private void password_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_fieldMouseClicked
        if(password_field.getText().equals("Password")){password_field.setText("");}
    }//GEN-LAST:event_password_fieldMouseClicked

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed
    private static Point point = new Point();
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel login_panel;
    private javax.swing.JTextField password_field;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
